name: ml
channels:
- conda-forge
- districtdatalabs
- defaults
dependencies:
- python=3.9
- scikit-learn=1.1.2
- numpy=1.23.3
- scipy=1.9.1
- theano=1.0.5
- tensorflow=2.9.1
- pytorch=1.12.1
- pandas=1.4.4
- matplotlib=3.5.3
- seaborn=0.12.0
- pylint
- jupyter
- jupyterlab
- notebook
- ipywidgets
- pip=22.3
- yellowbrick=1.5
- pip:
  - mlrose-hiive
  - mdptoolbox-hiive
#   - gradescope-utils
#   - subprocess32